[project]
name = "hioki-3545a-01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyvisa>=1.15.0",
    "pyvisa-py>=0.8.1",
]
